### ISSUE TITLE
怎么把peer0和orderer0的服务暴露出去？

### ISSUE THREAD

**Issue by mrwenhui** [horan-geeker/fabric-on-helm#1]
Error: Service "peer0" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[2].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'

**Comment by junwei000** [comment]
暴露出去的话就不要用 ClusterIP 这种方式了，改一下 peer0 和 orderer0 的 Service，把 type 改成 NodePort 并加上端口映射

**Comment by mrwenhui** [comment]
恩是的　如果默认　设置　spec.ClusterIP: None 就不能在线修改，必须删除service 修改　type:nodePort重新创建service 才能生效。
